const WA='250798488613';
const data=[
['Flyers & Posters','Product Launch','🔥','10,000 RWF','Bold promotional flyer for launches and offers.'],
['Flyers & Posters','Restaurant Special','🍽️','10,000 RWF','Food promotion with space for a menu item and price.'],
['Flyers & Posters','Church Event','⛪','10,000 RWF','Clean event announcement layout.'],
['Flyers & Posters','Sale Weekend','🏷️','10,000 RWF','High-impact sale and discount design.'],
['Flyers & Posters','Business Opening','🚀','10,000 RWF','Grand-opening promotional concept.'],
['Flyers & Posters','Beauty Promo','✨','10,000 RWF','Elegant beauty and service promotion.'],
['Invitations','Wedding Classic','💍','10,000 RWF','Elegant wedding invitation concept.'],
['Invitations','Birthday Party','🎂','10,000 RWF','Fun birthday invitation for any age.'],
['Invitations','Graduation','🎓','10,000 RWF','Celebration invitation for graduation events.'],
['Invitations','Baby Shower','🍼','10,000 RWF','Soft baby-shower invitation concept.'],
['Invitations','Engagement','💎','10,000 RWF','Romantic engagement invitation.'],
['Invitations','Private Party','🥂','10,000 RWF','Stylish private-event invitation.'],
['CV Design','Modern Professional','📄','10,000 RWF','Clean CV for applications and internships.'],
['CV Design','Minimal Executive','🧑‍💼','10,000 RWF','Structured professional resume layout.'],
['CV Design','Creative CV','🎨','10,000 RWF','Creative but readable CV concept.'],
['CV Design','Student CV','🎓','10,000 RWF','Simple student and graduate CV.'],
['CV Design','Corporate CV','💼','10,000 RWF','Formal corporate resume layout.'],
['CV Design','One-Page CV','⚡','10,000 RWF','Compact one-page application CV.'],
['Business Cards','Executive Card','🪪','10,000 RWF','Premium personal business card.'],
['Business Cards','Restaurant Card','🍽️','10,000 RWF','Business card for hospitality brands.'],
['Business Cards','Real Estate Card','🏠','10,000 RWF','Professional property-agent card.'],
['Business Cards','Creative Card','🎨','10,000 RWF','Bold card for creatives and freelancers.'],
['Business Cards','Service Card','🔧','10,000 RWF','Simple service-provider business card.'],
['Business Cards','Luxury Card','◆','10,000 RWF','Dark premium business-card concept.'],
['Social Media Graphics','Instagram Promo','📸','10,000 RWF','Square promotional post for Instagram.'],
['Social Media Graphics','New Product','🛍️','10,000 RWF','Product announcement graphic.'],
['Social Media Graphics','Quote Post','💬','10,000 RWF','Modern quote and brand-content design.'],
['Social Media Graphics','Restaurant Post','🍔','10,000 RWF','Food-focused social media post.'],
['Social Media Graphics','Service Promo','📲','10,000 RWF','Promote a service with a clear CTA.'],
['Social Media Graphics','Testimonial','⭐','10,000 RWF','Customer testimonial social post.'],
['Digital Banners','Website Hero','🌐','15,000 RWF','Wide hero banner for websites.'],
['Digital Banners','Facebook Cover','📘','15,000 RWF','Business social cover concept.'],
['Digital Banners','YouTube Banner','▶️','15,000 RWF','Channel banner with strong branding.'],
['Digital Banners','Event Banner','🎉','15,000 RWF','Wide event promotional banner.'],
['Digital Banners','Sale Banner','🔥','15,000 RWF','Promotional discount banner.'],
['Digital Banners','Business Header','🏢','15,000 RWF','Professional digital header.'],
['Document Formatting','Professional Report','📑','10,000 RWF','Clean report formatting and hierarchy.'],
['Document Formatting','Proposal','📋','10,000 RWF','Professional proposal document layout.'],
['Document Formatting','Letterhead','✉️','10,000 RWF','Branded letter and document style.'],
['Document Formatting','Project Document','📚','10,000 RWF','Organized academic or project document.'],
['Document Formatting','Company Profile','🏢','10,000 RWF','Structured business profile document.'],
['Document Formatting','Certificate','🏅','10,000 RWF','Clean certificate layout.'],
['Menus & Price Lists','Restaurant Menu','🍴','20,000 RWF','Modern food menu with clear prices.'],
['Menus & Price Lists','Cafe Menu','☕','20,000 RWF','Coffee-shop menu concept.'],
['Menus & Price Lists','Bar Menu','🍹','20,000 RWF','Stylish nightlife menu concept.'],
['Menus & Price Lists','Service Price List','💰','20,000 RWF','Simple service pricing sheet.'],
['Menus & Price Lists','Salon Menu','💇','20,000 RWF','Beauty-service menu and prices.'],
['Menus & Price Lists','Hotel Menu','🏨','20,000 RWF','Hospitality menu layout.'],
['Event Promotions','Concert Promo','🎤','30,000 RWF','High-energy event poster concept.'],
['Event Promotions','Birthday Event','🎂','30,000 RWF','Full event promotional design.'],
['Event Promotions','Business Conference','🎙️','30,000 RWF','Professional conference promotion.'],
['Event Promotions','Sports Event','🏆','30,000 RWF','Energetic sports-event visual.'],
['Event Promotions','Networking Night','🤝','30,000 RWF','Modern networking-event promotion.'],
['Event Promotions','Festival Promo','🎪','30,000 RWF','Bold festival promotional concept.'],
['Business Promotional Materials','New Business','🚀','30,000 RWF','Launch kit concept for a new business.'],
['Business Promotional Materials','Special Offer','🏷️','30,000 RWF','Branded offer and promotion concept.'],
['Business Promotional Materials','Service Campaign','📣','30,000 RWF','Campaign graphic for a service.'],
['Business Promotional Materials','Product Campaign','📦','30,000 RWF','Product campaign starter concept.'],
['Business Promotional Materials','Brand Announcement','📢','30,000 RWF','Professional announcement visual.'],
['Business Promotional Materials','Business Profile','💼','30,000 RWF','Promotional profile concept.']
];
const colors=[['#17271d','#b7ff3c'],['#241b17','#ffbd72'],['#151f2a','#8dd8ff'],['#271b28','#ff8bd4'],['#1b2420','#d6ff75'],['#211f17','#ffe07d']];
const cats=['All',...new Set(data.map(x=>x[0]))];let active='All',query='';
const filters=document.querySelector('#filters'),grid=document.querySelector('#templates'),count=document.querySelector('#count');
cats.forEach(c=>{const b=document.createElement('button');b.className='filter'+(c==='All'?' active':'');b.textContent=c;b.onclick=()=>{active=c;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};filters.appendChild(b)});
document.querySelector('#search').oninput=e=>{query=e.target.value.toLowerCase();render()};
function render(){const items=data.filter(x=>(active==='All'||x[0]===active)&&(!query||x[1].toLowerCase().includes(query)||x[0].toLowerCase().includes(query)));count.textContent=items.length+' templates';grid.innerHTML=items.map((x,i)=>{const c=colors[i%colors.length];return '<article class="card" data-i="'+data.indexOf(x)+'"><div class="preview" style="background:linear-gradient(135deg,'+c[0]+','+c[0]+' 55%,#090d0b);color:'+c[1]+'"><span class="p-tag">'+x[0]+'</span><span class="p-title">'+x[2]+' '+x[1]+'</span><span class="p-line"></span></div><div class="card-body"><h3>'+x[1]+'</h3><div class="meta"><span>'+x[0]+'</span><span class="price">'+x[3]+'</span></div></div></article>'}).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>open(+c.dataset.i))}
function open(i){const x=data[i],c=colors[i%colors.length],p=document.querySelector('#modalPreview');p.style.background='linear-gradient(135deg,'+c[0]+','+c[0]+' 55%,#090d0b)';p.style.color=c[1];p.innerHTML='<div style="padding:32px;font:800 12px DM Sans;letter-spacing:3px">'+x[0].toUpperCase()+'</div><div style="padding:32px;font:700 56px/1 Space Grotesk">'+x[2]+' '+x[1]+'</div>';document.querySelector('#modalCat').textContent=x[0];document.querySelector('#modalTitle').textContent=x[1];document.querySelector('#modalDesc').textContent=x[4];document.querySelector('#modalPrice').textContent=x[3];document.querySelector('#modalWhatsApp').href='https://wa.me/'+WA+'?text='+encodeURIComponent('Hello Enzo, I want the "'+x[1]+'" template from '+x[0]+'. Please customize it for me.');document.querySelector('#modal').classList.add('open');document.querySelector('#modal').setAttribute('aria-hidden','false')}
document.querySelector('#close').onclick=close;document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')close()};document.onkeydown=e=>{if(e.key==='Escape')close()};function close(){document.querySelector('#modal').classList.remove('open');document.querySelector('#modal').setAttribute('aria-hidden','true')}render();